# Generated by Django 5.1.7 on 2025-04-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_empleado_fdw'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
