# Generated by Django 5.1.7 on 2025-04-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_password_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fechaingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='persona',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
