# Generated by Django 5.1.7 on 2025-04-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_fechaingreso_alter_usuario_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellidomaterno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellidopaterno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
