# Generated by Django 5.1.7 on 2025-05-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0005_alter_usuario_apellidomaterno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurso', models.CharField(max_length=50)),
                ('accion', models.CharField(max_length=10)),
            ],
            options={
                'unique_together': {('recurso', 'accion')},
            },
        ),
        migrations.AddField(
            model_name='roles',
            name='permisos',
            field=models.ManyToManyField(blank=True, to='usuarios.permission'),
        ),
    ]
