# Generated by Django 5.1.7 on 2025-07-10 20:11

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('usuarios', '0007_alter_empleado_fdw_options_alter_permission_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('RESTORE', 'Restaurar'), ('LOGIN', 'Iniciar Sesión'), ('LOGOUT', 'Cerrar Sesión'), ('RESET_PASSWORD', 'Resetear Contraseña'), ('CHANGE_PASSWORD', 'Cambiar Contraseña'), ('MIGRATE_USER', 'Migrar Usuario'), ('ACTIVATE_USER', 'Activar Usuario'), ('DEACTIVATE_USER', 'Desactivar Usuario'), ('ASSIGN_ROLE', 'Asignar Rol'), ('REVOKE_ROLE', 'Revocar Rol'), ('APPROVE', 'Aprobar'), ('REJECT', 'Rechazar'), ('TRANSFER', 'Transferir'), ('CUSTOM', 'Acción Personalizada')], db_index=True, max_length=20)),
                ('accion_personalizada', models.CharField(blank=True, help_text='Descripción cuando accion=CUSTOM', max_length=100)),
                ('object_id', models.CharField(db_index=True, max_length=100)),
                ('objeto_representacion', models.CharField(max_length=200)),
                ('app_label', models.CharField(db_index=True, max_length=50)),
                ('model_name', models.CharField(db_index=True, max_length=50)),
                ('detalles', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.AlterModelOptions(
            name='empleado_fdw',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='permission',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permission',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='eliminado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permission',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 10, 20, 11, 13, 898839, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permission',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='roles',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roles',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='roles',
            name='eliminado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='roles',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roles',
            name='es_sistema',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roles',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roles',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='bloqueado_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='eliminado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='intentos_login_fallidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password_reset_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passwords_reseteados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password_reset_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password_reset_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultimo_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='accion',
            field=models.CharField(choices=[('crear', 'Crear'), ('leer', 'Leer'), ('actualizar', 'Actualizar'), ('eliminar', 'Eliminar')], max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'eliminado': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.roles'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['codigocotel'], name='usuarios_us_codigoc_bafaa3_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['is_active', 'eliminado'], name='usuarios_us_is_acti_47dfe5_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rol'], name='usuarios_us_rol_id_a19cc7_idx'),
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.CheckConstraint(condition=models.Q(('recurso__regex', '^[a-z0-9-_]+$')), name='permission_recurso_format'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['app_label', 'model_name', '-fecha_hora'], name='usuarios_au_app_lab_3bd95a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['usuario', '-fecha_hora'], name='usuarios_au_usuario_232038_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['accion', '-fecha_hora'], name='usuarios_au_accion_936c86_idx'),
        ),
    ]
