# Generated by Django 5.1.7 on 2025-07-11 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auditlog_alter_empleado_fdw_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='permission',
            name='permission_recurso_format',
        ),
    ]
