# Generated by Django 5.1.7 on 2025-06-09 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0006_formapago_plancomercial_tiposervicio_tipotramite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'almacenes_componente',
            },
        ),
        migrations.CreateModel(
            name='EquipoONU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(max_length=50, unique=True)),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('gpon_serial', models.CharField(max_length=100, unique=True)),
                ('serial_manufacturer', models.CharField(max_length=100, unique=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'almacenes_equipo_onu',
            },
        ),
        migrations.CreateModel(
            name='EstadoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'almacenes_estado_equipo',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'almacenes_marca',
            },
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'almacenes_tipo_equipo',
            },
        ),
        migrations.CreateModel(
            name='EquipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('fecha_desasignacion', models.DateField(blank=True, null=True)),
                ('estado_asignacion', models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.contrato')),
                ('equipo_onu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.equipoonu')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.servicio')),
            ],
            options={
                'db_table': 'almacenes_equipo_servicio',
            },
        ),
        migrations.AddField(
            model_name='equipoonu',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacenes.estadoequipo'),
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=50, unique=True)),
                ('proveedor', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.tiposervicio')),
            ],
            options={
                'db_table': 'almacenes_lote',
            },
        ),
        migrations.AddField(
            model_name='equipoonu',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.lote'),
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_modelo', models.IntegerField(unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.marca')),
                ('tipo_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.tipoequipo')),
            ],
            options={
                'db_table': 'almacenes_modelo',
                'unique_together': {('marca', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='equipoonu',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.modelo'),
        ),
        migrations.AddField(
            model_name='equipoonu',
            name='tipo_equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.tipoequipo'),
        ),
        migrations.CreateModel(
            name='LoteDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='almacenes.lote')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.modelo')),
            ],
            options={
                'db_table': 'almacenes_lote_detalle',
                'unique_together': {('lote', 'modelo')},
            },
        ),
        migrations.CreateModel(
            name='ModeloComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.SmallIntegerField(default=1)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.componente')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.modelo')),
            ],
            options={
                'db_table': 'almacenes_modelo_componente',
                'unique_together': {('modelo', 'componente')},
            },
        ),
    ]
