# Generated by Django 5.1.7 on 2025-09-08 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(default='#6B7280', max_length=7)),
                ('es_final', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado de Devolución',
                'verbose_name_plural': 'Estados de Devolución',
                'db_table': 'almacenes_estado_devolucion',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(default='#6B7280', help_text='Color hex para UI', max_length=7)),
                ('es_final', models.BooleanField(default=False, help_text='Indica si es un estado final')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado de Lote',
                'verbose_name_plural': 'Estados de Lote',
                'db_table': 'almacenes_estado_lote',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoMaterialGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=25, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(default='#6B7280', max_length=7)),
                ('permite_consumo', models.BooleanField(default=False, help_text='Si permite consumir en servicios')),
                ('permite_traspaso', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado de Material General',
                'verbose_name_plural': 'Estados de Material General',
                'db_table': 'almacenes_estado_material_general',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoMaterialONU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(default='#6B7280', max_length=7)),
                ('permite_asignacion', models.BooleanField(default=False, help_text='Si permite asignar a servicios')),
                ('permite_traspaso', models.BooleanField(default=True, help_text='Si permite traspasos')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado de Material ONU',
                'verbose_name_plural': 'Estados de Material ONU',
                'db_table': 'almacenes_estado_material_onu',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoTraspaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(default='#6B7280', max_length=7)),
                ('es_final', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado de Traspaso',
                'verbose_name_plural': 'Estados de Traspaso',
                'db_table': 'almacenes_estado_traspaso',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Respuesta de Proveedor',
                'verbose_name_plural': 'Respuestas de Proveedor',
                'db_table': 'almacenes_respuesta_proveedor',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Almacén',
                'verbose_name_plural': 'Tipos de Almacén',
                'db_table': 'almacenes_tipo_almacen',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Ingreso',
                'verbose_name_plural': 'Tipos de Ingreso',
                'db_table': 'almacenes_tipo_ingreso',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('simbolo', models.CharField(help_text='Símbolo de la unidad (m, kg, pza, etc.)', max_length=10)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'almacenes_unidad_medida',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='material',
            name='codigo_barras',
        ),
        migrations.AddField(
            model_name='almacen',
            name='codigo_cotel_encargado',
            field=models.CharField(blank=True, help_text='Código COTEL del encargado (se buscará automáticamente)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='almacen',
            name='encargado',
            field=models.ForeignKey(blank=True, help_text='Encargado del almacén (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='almacenes_a_cargo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='material',
            name='gpon_serial',
            field=models.CharField(blank=True, help_text='GPON Serial para equipos únicos', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='mac_address',
            field=models.CharField(blank=True, help_text='MAC Address para equipos únicos', max_length=17, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='serial_manufacturer',
            field=models.CharField(blank=True, help_text='D-SN/Serial Manufacturer para equipos únicos', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='devolucionproveedor',
            name='estado',
            field=models.ForeignKey(help_text='Estado actual de la devolución', on_delete=django.db.models.deletion.CASCADE, to='almacenes.estadodevolucion'),
        ),
        migrations.AlterField(
            model_name='entregaparciallote',
            name='estado_entrega',
            field=models.ForeignKey(help_text='Estado de esta entrega parcial', on_delete=django.db.models.deletion.CASCADE, to='almacenes.estadolote'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='estado',
            field=models.ForeignKey(help_text='Estado actual del lote', on_delete=django.db.models.deletion.CASCADE, to='almacenes.estadolote'),
        ),
        migrations.AlterField(
            model_name='material',
            name='estado_general',
            field=models.ForeignKey(blank=True, help_text='Estado para materiales por cantidad', null=True, on_delete=django.db.models.deletion.CASCADE, to='almacenes.estadomaterialgeneral'),
        ),
        migrations.AlterField(
            model_name='material',
            name='estado_onu',
            field=models.ForeignKey(blank=True, help_text='Estado específico para equipos únicos (ONU, etc.)', null=True, on_delete=django.db.models.deletion.CASCADE, to='almacenes.estadomaterialonu'),
        ),
        migrations.AlterField(
            model_name='traspasoalmacen',
            name='estado',
            field=models.ForeignKey(help_text='Estado actual del traspaso', on_delete=django.db.models.deletion.CASCADE, to='almacenes.estadotraspaso'),
        ),
        migrations.AlterField(
            model_name='devolucionproveedor',
            name='respuesta_proveedor',
            field=models.ForeignKey(blank=True, help_text='Respuesta del proveedor a la devolución', null=True, on_delete=django.db.models.deletion.CASCADE, to='almacenes.respuestaproveedor'),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='tipo',
            field=models.ForeignKey(help_text='Tipo de almacén', on_delete=django.db.models.deletion.CASCADE, to='almacenes.tipoalmacen'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='tipo_ingreso',
            field=models.ForeignKey(help_text='Tipo de ingreso del lote', on_delete=django.db.models.deletion.CASCADE, to='almacenes.tipoingreso'),
        ),
        migrations.AlterField(
            model_name='material',
            name='tipo_origen',
            field=models.ForeignKey(help_text='Tipo de origen del material', on_delete=django.db.models.deletion.CASCADE, to='almacenes.tipoingreso'),
        ),
        migrations.CreateModel(
            name='TipoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('requiere_inspeccion_inicial', models.BooleanField(default=False)),
                ('es_unico', models.BooleanField(default=False, help_text='True para equipos únicos (ONU), False para materiales por cantidad')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_material_creados', to=settings.AUTH_USER_MODEL)),
                ('unidad_medida_default', models.ForeignKey(help_text='Unidad de medida por defecto', on_delete=django.db.models.deletion.CASCADE, to='almacenes.unidadmedida')),
            ],
            options={
                'verbose_name': 'Tipo de Material',
                'verbose_name_plural': 'Tipos de Material',
                'db_table': 'almacenes_tipo_material',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AlterField(
            model_name='material',
            name='tipo_material',
            field=models.ForeignKey(help_text='Tipo de material', on_delete=django.db.models.deletion.CASCADE, to='almacenes.tipomaterial'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='tipo_material',
            field=models.ForeignKey(help_text='Tipo de material que representa este modelo', on_delete=django.db.models.deletion.CASCADE, to='almacenes.tipomaterial'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='unidad_medida',
            field=models.ForeignKey(help_text='Unidad de medida para este modelo', on_delete=django.db.models.deletion.CASCADE, to='almacenes.unidadmedida'),
        ),
    ]
