# Generated by Django 5.1.7 on 2025-09-10 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0003_estadodevolucion_estadolote_estadomaterialgeneral_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipoonu',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='equipoonu',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='equipoonu',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='equipoonu',
            name='tipo_equipo',
        ),
        migrations.RemoveField(
            model_name='equiposervicio',
            name='equipo_onu',
        ),
        migrations.RemoveField(
            model_name='equiposervicio',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='equiposervicio',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='material',
            name='tipo_equipo',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='tipo_equipo',
        ),
        migrations.DeleteModel(
            name='EstadoEquipo',
        ),
        migrations.DeleteModel(
            name='EquipoONU',
        ),
        migrations.DeleteModel(
            name='EquipoServicio',
        ),
        migrations.DeleteModel(
            name='TipoEquipo',
        ),
    ]
