# Generated by Django 5.1.7 on 2025-09-14 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0004_remove_equipoonu_estado_remove_equipoonu_lote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='equipo_original',
            field=models.ForeignKey(blank=True, help_text='Equipo original que está siendo reemplazado (para reingresos)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reingresos', to='almacenes.material'),
        ),
        migrations.AddField(
            model_name='material',
            name='motivo_reingreso',
            field=models.TextField(blank=True, help_text='Motivo del reingreso/reposición'),
        ),
        migrations.AddField(
            model_name='material',
            name='numero_entrega_parcial',
            field=models.PositiveIntegerField(blank=True, help_text='Número de entrega parcial a la que pertenece este material', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='numero_informe_laboratorio',
            field=models.CharField(blank=True, help_text='Número de informe de laboratorio', max_length=50),
        ),
        migrations.AddField(
            model_name='material',
            name='observaciones_laboratorio',
            field=models.JSONField(blank=True, default=dict, help_text='Observaciones detalladas del laboratorio'),
        ),
        migrations.CreateModel(
            name='InspeccionLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_informe', models.CharField(max_length=50, unique=True)),
                ('serie_logica_ok', models.BooleanField(help_text='Serie lógica coincide')),
                ('wifi_24_ok', models.BooleanField(help_text='WiFi 2.4GHz funciona')),
                ('wifi_5_ok', models.BooleanField(help_text='WiFi 5GHz funciona')),
                ('puerto_ethernet_ok', models.BooleanField(help_text='Puerto Ethernet OK')),
                ('puerto_lan_ok', models.BooleanField(help_text='Puerto LAN OK')),
                ('aprobado', models.BooleanField()),
                ('observaciones_tecnico', models.TextField(blank=True)),
                ('comentarios_adicionales', models.TextField(blank=True)),
                ('fallas_detectadas', models.JSONField(blank=True, default=list)),
                ('tecnico_revisor', models.CharField(blank=True, max_length=50)),
                ('tiempo_inspeccion_minutos', models.PositiveIntegerField(default=0)),
                ('fecha_inspeccion', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones_laboratorio', to='almacenes.material')),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'almacenes_inspeccion_laboratorio',
                'ordering': ['-fecha_inspeccion'],
            },
        ),
    ]
