# Generated by Django 5.1.7 on 2025-09-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0005_material_equipo_original_material_motivo_reingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='serial_manufacturer',
            field=models.CharField(blank=True, help_text='D-SN/Serial Manufacturer para equipos únicos (opcional)', max_length=100, null=True),
        ),
    ]
