# Generated by Django 5.1.7 on 2025-09-17 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0006_alter_material_serial_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_reemplazo',
            field=models.OneToOneField(blank=True, help_text='Material que reemplaza a este (en caso de devolución/reposición)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_original', to='almacenes.material'),
        ),
    ]
