# Generated by Django 5.1.7 on 2025-09-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0007_material_material_reemplazo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorSolicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sector Solicitante',
                'verbose_name_plural': 'Sectores Solicitantes',
                'db_table': 'almacenes_sector_solicitante',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
