# Generated by Django 5.1.7 on 2025-09-20 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0008_sectorsolicitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='sector_solicitante',
            field=models.ForeignKey(default=1, help_text='Sector que solicita los materiales', on_delete=django.db.models.deletion.CASCADE, to='almacenes.sectorsolicitante'),
            preserve_default=False,
        ),
    ]
