# Generated by Django 5.1.7 on 2025-09-20 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0009_lote_sector_solicitante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devolucionproveedor',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='devolucionproveedor',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='devolucionproveedor',
            name='lote_origen',
        ),
        migrations.RemoveField(
            model_name='devolucionproveedor',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='devolucionproveedor',
            name='respuesta_proveedor',
        ),
        migrations.RemoveField(
            model_name='historialmaterial',
            name='devolucion_relacionada',
        ),
        migrations.DeleteModel(
            name='DevolucionMaterial',
        ),
        migrations.DeleteModel(
            name='EstadoDevolucion',
        ),
        migrations.DeleteModel(
            name='RespuestaProveedor',
        ),
        migrations.DeleteModel(
            name='DevolucionProveedor',
        ),
    ]
