# Generated by Django 5.1.7 on 2025-09-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0010_remove_devolucionproveedor_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccionlaboratorio',
            name='otros_ok',
            field=models.BooleanField(default=True, help_text='Otras pruebas adicionales OK'),
        ),
        migrations.AddField(
            model_name='inspeccionlaboratorio',
            name='puerto_catv_ok',
            field=models.BooleanField(default=True, help_text='Puerto CATV (TV por cable) funciona'),
        ),
        migrations.AddField(
            model_name='inspeccionlaboratorio',
            name='puerto_telefonia_rf_ok',
            field=models.BooleanField(default=True, help_text='Puerto de Telefonía RF (POTS/FXS) funciona'),
        ),
        migrations.AlterField(
            model_name='inspeccionlaboratorio',
            name='comentarios_adicionales',
            field=models.TextField(blank=True, help_text='Comentarios adicionales o notas finales'),
        ),
        migrations.AlterField(
            model_name='inspeccionlaboratorio',
            name='observaciones_tecnico',
            field=models.TextField(blank=True, help_text="Observaciones principales del técnico (incluir detalles de 'otros' aquí)"),
        ),
    ]
