# Generated by Django 5.1.7 on 2025-09-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0011_inspeccionlaboratorio_otros_ok_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccionlaboratorio',
            name='comentarios_adicionales',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inspeccionlaboratorio',
            name='observaciones_tecnico',
            field=models.TextField(blank=True),
        ),
    ]
