# Generated by Django 5.1.7 on 2025-05-21 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_alter_contrato_numero_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='numero_contrato',
            field=models.CharField(blank=True, max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='El número de contrato debe tener exactamente 8 dígitos.', regex='^\\d{8}$')]),
        ),
    ]
