# Generated by Django 5.1.7 on 2025-05-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_alter_contrato_numero_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='numero_contrato',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
