# Generated by Django 5.1.7 on 2025-06-06 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_alter_contrato_numero_contrato'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicio',
            unique_together={('contrato', 'tipo_servicio')},
        ),
    ]
