# Generated by Django 5.1.7 on 2025-06-06 18:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('contratos', '0005_alter_servicio_unique_together'),
    ]

    operations = [
        # PRIMERO: Crear todas las tablas nuevas
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contratos_forma_pago',
            },
        ),
        migrations.CreateModel(
            name='PlanComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_plan', models.CharField(max_length=50, unique=True)),
                ('velocidad_descarga', models.IntegerField(blank=True, null=True)),
                ('velocidad_subida', models.IntegerField(blank=True, null=True)),
                ('precio_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('precio_instalacion', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contratos_plan_comercial',
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contratos_tipo_servicio',
            },
        ),
        migrations.CreateModel(
            name='TipoTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contratos_tipo_tramite',
            },
        ),

        # SEGUNDO: Agregar campos a tablas existentes (sin FK a las nuevas tablas)
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(default='La Paz', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(
                choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('INACTIVO', 'Inactivo')],
                default='ACTIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_alternativo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='zona',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contrato',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='direccion_instalacion',
            field=models.TextField(default='Miraflores'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='estado_contrato',
            field=models.CharField(
                choices=[('PENDIENTE', 'Pendiente'), ('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'),
                         ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='contrato',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='estado_servicio',
            field=models.CharField(
                choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('CANCELADO', 'Cancelado')],
                default='ACTIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='servicio',
            name='fecha_activacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='fecha_desactivacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),

        # TERCERO: Cambiar nombres de tablas
        migrations.AlterModelTable(
            name='cliente',
            table='contratos_cliente',
        ),
        migrations.AlterModelTable(
            name='contrato',
            table='contratos_contrato',
        ),
        migrations.AlterModelTable(
            name='servicio',
            table='contratos_servicio',
        ),

        # CUARTO: Remover unique_together temporal antes de agregar las FK
        migrations.AlterUniqueTogether(
            name='servicio',
            unique_together=set(),
        ),

        # QUINTO: Agregar las FK a las nuevas tablas (ahora que ya existen)
        migrations.AddField(
            model_name='plancomercial',
            name='tipo_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.tiposervicio'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='forma_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='contratos.formapago'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_tramite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='contratos.tipotramite'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='plan_comercial',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='contratos.plancomercial'),
        ),

        # SEXTO: Crear modelo que depende de los anteriores
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ot', models.CharField(blank=True, max_length=20, unique=True)),
                ('tecnico_asignado', models.CharField(blank=True, max_length=100)),
                ('fecha_asignacion', models.DateField(blank=True, null=True)),
                ('fecha_programada', models.DateField(blank=True, null=True)),
                ('fecha_ejecucion', models.DateField(blank=True, null=True)),
                ('estado_ot', models.CharField(
                    choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADA', 'Asignada'), ('EN_PROCESO', 'En Proceso'),
                             ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE',
                    max_length=20)),
                ('tipo_trabajo', models.CharField(max_length=50)),
                ('observaciones_tecnico', models.TextField(blank=True)),
                ('materiales_utilizados', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_trabajo',
                                   to='contratos.contrato')),
            ],
            options={
                'db_table': 'contratos_orden_trabajo',
            },
        ),

        # SEPTIMO: Establecer unique_together final y remover campos
        migrations.AlterUniqueTogether(
            name='servicio',
            unique_together={('contrato', 'plan_comercial')},
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='tipo_servicio',
        ),
    ]