# Generated by Django 5.1.7 on 2025-06-16 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_formapago_plancomercial_tiposervicio_tipotramite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='plan_comercial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.plancomercial'),
        ),
    ]
